### ISSUE TITLE
Support for ppc64le and s390x?

### ISSUE THREAD

**Issue by sanchezl** [apache/couchdb-docker#66] opened 2018-02-01 20:40 UTC
## Expected Behavior
`docker pull couchdb` on `ppc64le` or `s390x` should work.

## Current Behavior
Only `amd64` images are available.

## Possible Solution
https://github.com/docker-library/official-images#multiple-architectures

## Steps to Reproduce (for bugs)
`docker pull couchdb` on `ppc64le` or `s390x` machines.

## Context
I currently have to pull `git@github.com:apache/couchdb-docker.git` and build `couchdb` images myself for platforms other than `amd64`. Now that Docker hub supports multiple architectures, it would be great if couchdb images were available for non-`amd64` architectures.

## Your Environment
ubuntu64 for ppc64le and s390x

**Comment by wohali** [comment] 2018-02-01 21:24
Hi @sanchezl , thanks for your interest.

A prerequisite for any sort of released Docker image is that Apache CouchDB can consistently run, and pass, all tests on this platform as part of our CI workflow. Both of these platforms are currently absent from our matrix.

For `ppc64le`, work is ongoing to add this to the CouchDB CI workflow, see apache/couchdb#1121. Currently, there are other tests failing in the Jenkins workflow blocking this work. (I need Jenkins to be all-green before modifying the configuration further.) If you are in a position to help resolve these issues in the code base, your support is welcome - please contact us on the [Developer mailing list](http://couchdb.apache.org/#mailing-lists). /cc @jiangphcn 

Unfortunately, there are known issues for running CouchDB on `s390x`; see discussion on JIRA [COUCHDB-3261](https://issues.apache.org/jira/browse/COUCHDB-3261), which stalled out due to lack of support from IBM to fix the *problem* rather than the *symptom*. (Sweeping test cases under the rug is not an acceptable alternative.) We won't release an `s390x` image until the full test suite runs cleanly and repeatably.

Further, the Apache Software Foundation does not have CI resources for `s390x`, so regression is entirely likely. Perhaps IBM is willing to donate compute and build resources for this platform so we can add it to our CI matrix? /cc @kocolosk 

Finally, a PR is already outstanding to support building of multi-architecture Docker images, PR #60 . This is blocked until apache/couchdb#1121 is done. /cc @sudswas 

I am closing this ticket as too broad (since it covers two platforms, one of which is much farther along than the other). I will open separate tracking issues for each platform; please follow-up with us on those if you are able to contribute further.

**Closed by wohali** 2018-02-01 21:24 UTC

**Comment by junaruga** [comment] 2019-12-03 13:33
Hi I just came here by a co-incidence when searching something.

> Further, the Apache Software Foundation does not have CI resources for s390x, so regression is entirely likely. Perhaps IBM is willing to donate compute and build resources for this platform so we can add it to our CI matrix?

Now Travis has the native ppc64le and s390x CI resources. You can add it to your CI matrix.

Here is the article.
https://blog.travis-ci.com/2019-11-12-multi-cpu-architecture-ibm-power-ibm-z

**Comment by wohali** [comment] 2019-12-03 17:19
We've been having very very bad problems with Travis, and are migrating off of it entirely.

**Comment by ghatwala** [comment] 2019-12-04 13:44
@wohali  - Would you like to elaborate on the issues u faced with **Travis** ?

**Comment by michal-at-travisci** [comment] 2019-12-04 16:08
Hi @wohali I'm sorry to hear about this. Do you mind if I reach out on your slack? I am interested in finding out what issues pushed you away from Travis CI.

**Comment by wohali** [comment] 2019-12-04 19:33
@michal-at-travisci I don't use the Slack, though I am registered there.

You can email me at wohali @ apache.org to follow-up if you like.

**Comment by michal-at-travisci** [comment] 2019-12-05 14:05
Thank you, I will e-mail you shortly.

śr., 4 gru 2019, 20:33 użytkownik Joan Touzet <notifications@github.com>
napisał:
