### ISSUE TITLE
Set single_node using an environment variable?

### ISSUE THREAD

**Issue by coreyfarrell** [apache/couchdb-docker#184] opened 2020-07-03 08:53 UTC
## Expected Behavior
I'm looking for a way to run a temporary couchdb container with `single_node=true` set.

## Current Behavior
`single_mode=false` is the default, this causes system databases to not be created and spams the log with failed access.  The default be changed without mounting a volume or creating an inherited container image.

## Possible Solution
Enable support for `-e COUCHDB_SINGLE_NODE=true` from the initialization script.

## Context
I'm trying to use this container as part of an automated test suite for a daemon that will use couchdb for storage.  The hope is to use the following command to start a docker container:
```sh
podman run \
  --rm \
  -e COUCHDB_USER=admin \
  -e COUCHDB_PASSWORD=admin \
  -e COUCHDB_SINGLE_NODE=true \
  -p 127.0.0.1:5984:5984 \
  docker.io/library/couchdb:3
```

I attempted to mount ./fixtures/couchdb to /opt/couchdb/etc/local.d with a local.ini in that folder.  I received SELinux errors first then adding the `:Z` option to the folder mount gave an error `relabeling content in /usr is not allowed` (my code is under `/usr/src`).  I then tried using `mktemp -d` and copying my local.ini to that temp directory.  This allowed couchdb-docker to start and recognize `single_node=true` but unfortunately resulted in the temporary directory ownership being taken over (so removing it after the container runs would require sudo).

## Your Environment
* Version used: 3.1.0
* Browser Name and version: None
* Operating System and version (desktop or mobile): Fedora 32, using podman 2.0.1.
* Link to your project: N/A

**Comment by janl** [comment] 2020-07-03 09:03
Duplicate of https://github.com/apache/couchdb/discussions/2948

basically: PRs welcome ;)

**Closed by janl** 2020-07-03 09:03 UTC

**Comment by coreyfarrell** [comment] 2020-07-05 14:49
I would be happy to make a PR for this but it seems like @wohali has strong objection to adding this environmental variable?

**Comment by wohali** [comment] 2020-07-05 19:07
I am indeed -1 on the concept, for all the reasons previously stated, but if @janl wants to override me, I haven't decided if I will actually throw a technical veto against it.

**Comment by janl** [comment] 2020-07-06 07:59
Oops sorry, I must have missed those objections, where can I find them?

**Comment by janl** [comment] 2020-07-06 08:30
ah I found this: https://github.com/apache/couchdb/discussions/2948#discussioncomment-29228

I’d be okay for “one more env var” if this was the last one, as it is a basic setup thing (kinda like admin user/pass) , but I’m equally fine with letting folks do this the proper way.
