### ISSUE TITLE
Tag 2 is broken on docker hub. 

### ISSUE THREAD

**Issue by newtewt** [apache/couchdb-docker#196] opened 2021-02-03 18:35 UTC
## Expected Behavior

Running `docker pull couchdb:2` on ubuntu 18.04 pulls the tag for 2. 

## Current Behavior

Running `docker pull couchdb:2` on ubuntu 18.04 returns 

```
Unable to find image 'couchdb:2' locally
2: Pulling from library/couchdb
docker: no matching manifest for linux/amd64 in the manifest list entries.
```

## Possible Solution

Using 2.3.1 instead of just 2 works fine. 

## Steps to Reproduce (for bugs)

1. Clear local images of couchdb `docker image prune`
2. Pull couchdb2 `docker pull couchdb:2`
3. Failure occurs

## Context

Breaks the build process we have that runs `docker run -d -p 5984:5984 --name couch couchdb:2`

## Your Environment

* Version used: 2
* Browser Name and version: chrome
* Operating System and version (desktop or mobile):  desktop and githubactions ci
* Link to your project:

**Comment by wohali** [comment] 2021-02-03 19:22
As far as I know, this is Docker's issue, not ours.

We've done everything necessary on our part here: https://github.com/docker-library/official-images/blob/master/library/couchdb

This file tells Docker to build the official image, with the exact same commit used for the 2.3.1, 2.3 and 2 tags.

I also cannot reproduce this here:

```bash
$ docker pull couchdb:2
2: Pulling from library/couchdb
8aff230071c9: Pull complete
276e247f0cd6: Pull complete
71b2066d261b: Pull complete
bd4d1b0a4337: Pull complete
83230eedf25e: Pull complete
d50eec4085f7: Pull complete
3896d223e87c: Pull complete
9189261b9f49: Pull complete
0dd0e70fe85e: Pull complete
9cf6aed35787: Pull complete
0b404ef97452: Pull complete
Digest: sha256:ef82b77dd5ffec80f154c203d7a96df6934baa423b2a8b9450df6fd692472075
Status: Downloaded newer image for couchdb:2
docker.io/library/couchdb:2
$ docker inspect couchdb:2
[
    {
        "Id": "sha256:493c01c773ded205388203a5eb88aad25eb14e3009066d49089f04d5d011007a",
        "RepoTags": [
            "couchdb:2"
        ],
        "RepoDigests": [
            "couchdb@sha256:ef82b77dd5ffec80f154c203d7a96df6934baa423b2a8b9450df6fd692472075"
        ],
        "Parent": "",
        "Comment": "",
        "Created": "2021-01-12T03:53:46.011492486Z",
        "Container": "988fa3c111d40fab4dcc8e90aa7483836eb041af4ef57ff1388e3e11d98e3639",
        "ContainerConfig": {
            "Hostname": "988fa3c111d4",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "4369/tcp": {},
                "5984/tcp": {},
                "9100/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "GOSU_VERSION=1.11",
                "TINI_VERSION=0.18.0",
                "GPG_COUCH_KEY=8756C4F765C9AC3CB6B85D62379CE192D401AB61",
                "COUCHDB_VERSION=2.3.1"
            ],
            "Cmd": [
                "/bin/sh",
                "-c",
                "#(nop) ",
                "CMD [\"/opt/couchdb/bin/couchdb\"]"
            ],
            "Image": "sha256:12f27a3acbcb1e4147ddae4d7d71761ceab80b03f2d70aa68187dfcda49ddc2c",
            "Volumes": {
                "/opt/couchdb/data": {}
            },
            "WorkingDir": "",
            "Entrypoint": [
                "tini",
                "--",
                "/docker-entrypoint.sh"
            ],
            "OnBuild": null,
            "Labels": {
                "maintainer": "CouchDB Developers dev@couchdb.apache.org"
            }
        },
        "DockerVersion": "19.03.12",
        "Author": "",
        "Config": {
            "Hostname": "",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "4369/tcp": {},
                "5984/tcp": {},
                "9100/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "GOSU_VERSION=1.11",
                "TINI_VERSION=0.18.0",
                "GPG_COUCH_KEY=8756C4F765C9AC3CB6B85D62379CE192D401AB61",
                "COUCHDB_VERSION=2.3.1"
            ],
            "Cmd": [
                "/opt/couchdb/bin/couchdb"
            ],
            "Image": "sha256:12f27a3acbcb1e4147ddae4d7d71761ceab80b03f2d70aa68187dfcda49ddc2c",
            "Volumes": {
                "/opt/couchdb/data": {}
            },
            "WorkingDir": "",
            "Entrypoint": [
                "tini",
                "--",
                "/docker-entrypoint.sh"
            ],
            "OnBuild": null,
            "Labels": {
                "maintainer": "CouchDB Developers dev@couchdb.apache.org"
            }
        },
        "Architecture": "amd64",
        "Os": "linux",
        "Size": 200862407,
        "VirtualSize": 200862407,
        "GraphDriver": {
            "Data": {
                "LowerDir": "/var/lib/docker/overlay2/8fe6570a006b72adfd4a5963a279b0f36c50fa4e2398650b359293f9a06360be/diff:/var/lib/docker/overlay2/afcfa2cc286775d931abcdd60cfe78605f6d182fc96900724fee66fafb4f74e2/diff:/var/lib/docker/overlay2/c4d288455becc08ba55a78528d4b09c89c97ad0beea11a848a1244b1ebd08350/diff:/var/lib/docker/overlay2/d512e3bbe9fe4c3022065e190fad9a07afdeaef172fc7cb843f331746a1cf91a/diff:/var/lib/docker/overlay2/ed444d3acd52ce95994004c4eb9fc7d62fcaf1f432cb38c13baa4eaf4ad8acce/diff:/var/lib/docker/overlay2/ee98e4b53bb9d4210095cc2ee919f2a2a358c8c374b9121e09717164df418fc7/diff:/var/lib/docker/overlay2/59e007884bca51bc8acb5c861733b164862276c83ac38fd796ca59b4523ca38b/diff:/var/lib/docker/overlay2/03ad85d3f49aeddce41ef2daaba0810dc9aba7e81a50eb22f894f0f526f859e3/diff:/var/lib/docker/overlay2/ff23242edd0c33816f2e410a609ecef9ace8c8d3827080c4e71de561fb2a8907/diff:/var/lib/docker/overlay2/999f7a767e92bafa6176c045cd55ea3750abc80d13aa8c60bb45cd9aa2cb3bcd/diff",
                "MergedDir": "/var/lib/docker/overlay2/42fe6c72350e8e20d5506dcef4f36829498d2bd9383ea5a9d7c336257bcfe054/merged",
                "UpperDir": "/var/lib/docker/overlay2/42fe6c72350e8e20d5506dcef4f36829498d2bd9383ea5a9d7c336257bcfe054/diff",
                "WorkDir": "/var/lib/docker/overlay2/42fe6c72350e8e20d5506dcef4f36829498d2bd9383ea5a9d7c336257bcfe054/work"
            },
            "Name": "overlay2"
        },
        "RootFS": {
            "Type": "layers",
            "Layers": [
                "sha256:3cb5179ea5db4b841700717b6b58201fcd16fb99eb4bacc76bad4ff658f2db7d",
                "sha256:0bf8e20ef2288f47456e9aab87831bd59d1ae5cb53d19e0db42fe7ef2ce84cb5",
                "sha256:761f1973c7947ad8e86b7ed2add0cc61d3a9f4c2dd03a936b646866bce4fa4da",
                "sha256:6c88cd149c2160b2df76d7de06a2aedb081694903e22057ed69578de953b095b",
                "sha256:ee15ce0ce0b203d23a4157426ac3368598a1a11b686995d28f09f6d1d814376c",
                "sha256:00b98c84bd7ba04c6c17952b0de2173f49dddea88cbef7d5ae3d2003dcdea8a9",
                "sha256:d197ac45f4d9923ea15ce3a5e5e853c9670151fb5afe9df0564ab9dac501b49b",
                "sha256:d1bb0f9bbba99379612c243a2adc7b6e97d7fad05ce555fd8256b6b406f3352b",
                "sha256:004e711adb47aa21e8735efc465ffc258099fb33be2ad4a4a742f10461e391eb",
                "sha256:6c3b83f4cf5788e8b857b3ff4ad5243ec72d1eccab15454a390c2630bf65a2e6",
                "sha256:f7b0e65ceb31301104464cdfa8c1a3471b79b32bfb5727f61574fb4e5903356e"
            ]
        },
        "Metadata": {
            "LastTagTime": "0001-01-01T00:00:00Z"
        }
    }
]
```

Closing for now - if you can show something we need to do otherwise, please let me know. (Perhaps you have changed your docker repo?)

**Closed by wohali** 2021-02-03 19:22 UTC

**Comment by newtewt** [comment] 2021-02-03 20:09
Thanks, looks like there was another push more recently and now the Tag for 2 is working again.
