### ISSUE TITLE
Unable to use 2.2.0 as base image

### ISSUE THREAD

**Issue by code-noggin** [apache/couchdb-docker#104] opened 2018-09-06 20:47 UTC
## Expected Behavior

I'm trying to use 2.2.0 as a base image for my own docker image. I should be able to run `apt-get update` in my Dockerfile without an error.
```
FROM couchdb:2.2.0
RUN apt-get update 
```

## Current Behavior

The `apt-get update` fails when fetching `https://apache.bintray.com/couchdb-deb/dists/stretch/InRelease` because the `apt-transport-https` package was purged at https://github.com/apache/couchdb-docker/blob/f429c1ccf22fe8cf7717383462fbf2f56e6d0301/2.2.0/Dockerfile#L138. 

Here's the build output:
```
docker build  .
Sending build context to Docker daemon  146.4kB
Step 1/16 : FROM couchdb:2.2.0
 ---> 44b2522e3e4a
Step 2/16 : RUN apt-get update
 ---> Running in e6de50b54b92
Get:1 http://security.debian.org/debian-security stretch/updates InRelease [94.3 kB]
Get:2 http://security.debian.org/debian-security stretch/updates/main amd64 Packages [393 kB]
Ign:3 http://cdn-fastly.deb.debian.org/debian stretch InRelease
Get:4 http://cdn-fastly.deb.debian.org/debian stretch-updates InRelease [91.0 kB]
Get:5 http://cdn-fastly.deb.debian.org/debian stretch Release [118 kB]
Get:6 http://cdn-fastly.deb.debian.org/debian stretch Release.gpg [2434 B]
Get:7 http://cdn-fastly.deb.debian.org/debian stretch-updates/main amd64 Packages [5148 B]
Get:8 http://cdn-fastly.deb.debian.org/debian stretch/main amd64 Packages [7099 kB]
Fetched 7802 kB in 2s (2943 kB/s)
Reading package lists...
E: The method driver /usr/lib/apt/methods/https could not be found.
E: Failed to fetch https://apache.bintray.com/couchdb-deb/dists/stretch/InRelease
E: Some index files failed to download. They have been ignored, or old ones used instead.
The command '/bin/sh -c apt-get update' returned a non-zero code: 100
```

## Possible Solution

Do not include `apt-transport-https` as one of the `buildDeps` at https://github.com/apache/couchdb-docker/blob/f429c1ccf22fe8cf7717383462fbf2f56e6d0301/2.2.0/Dockerfile#L114. 

## Steps to Reproduce (for bugs)

```
#!/bin/sh

cat <<-END-OF-DOCKERFILE > Dockerfile.couchdb_extension
        FROM couchdb:2.2.0
        RUN apt-get update
END-OF-DOCKERFILE

docker build -f Dockerfile.couchdb_extension .
```

## Context

I'm trying to create a custom docker image based on the official couchdb:2.2.0 docker image. My image will have custom couchdb config and run an additional application in the background.

## Your Environment

* Version used: `Docker version 18.06.1-ce, build e68fc7a`
* Browser Name and version: n/a
* Operating System and version (desktop or mobile): macOS High Sierra
* Link to your project: n/a

**Comment by wohali** [comment] 2018-09-07 02:41
Hi there, duplicate of #101. Our very next version of this will correct the problem. If you need to have a workaround sooner, you can build the couchdb image using the files from this repository yourself. Sorry for the inconvenience.

**Closed by wohali** 2018-09-07 02:41 UTC
