### ISSUE TITLE
Dockerfile with data

### ISSUE THREAD

**Issue by Maxima078** [apache/couchdb-docker#35] opened 2017-10-24 12:12 UTC
Hi, this is probably related to https://github.com/apache/couchdb-docker/issues/34 but just in case this is what I'm trying to do:

I'm preparing a Dockerfile from apache/couchdb:2.1.0. I want to overwrite local.ini and prepare data (default databases and _users database with design among other things). It was really easy to import my local.ini with the COPY command. But I cannot use ADD to import my own data folder, it's always erased by the container data. Here is my Dockerfile:

    FROM apache/couchdb:2.1.0
    MAINTAINER Max <maxima078@gmail.com>
    ADD /data /opt/test/data
    COPY local.ini /opt/couchdb/etc/local.ini

Is that even possible? 

Thanks for any hints.

**Comment by wohali** [comment] 2017-10-24 17:40
It is definitely possible, yes, there are people out there doing this today. You don't want ADD, you want to specify the volume on the `docker run` line using `-v` for both your ini files and for your data volume.

This is definitely a duplicate of #34.

**Closed by wohali** 2017-10-24 17:40 UTC

**Comment by Maxima078** [comment] 2017-10-25 14:33
Thank you for your answer. Indeed it works to prepare data in a folder and then at Docker Run specify the volume to this folder. There is just one problem, I copied fresh data from a previous Docker Run set up as single node from fauxton (/_utils/#/setup). Then I copied data to my futur volume folder and mount it with a new Docker run. From this moment my data are available and it's really cool but from the setup page it tells me I'm running in cluster mode and I cannot figure out why. Do you have any idea?

**Comment by wohali** [comment] 2017-10-25 18:59
The detection function for cluster vs. single mode is dependent upon whether or not the bind address for CouchDB is 127.0.0.1 or not. This only states whether or not the node is _capable_ of being configured in a cluster, not that it is actually joined to a cluster.

You can safely ignore this.
